services:
  rucio:
    ports:
      - "127.0.0.1:8443:443"
  ruciodb:
    ports:
      - "127.0.0.1:5432:5432"
  graphite:
    ports:
      - "127.0.0.1:8080:80"
  influxdb:
    ports:
      - "127.0.0.1:8086:8086"
  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  activemq:
    ports:
      - "127.0.0.1:61613:61613"
      - "127.0.0.1:8161:8161"
  mysql8:
    ports:
      - "127.0.0.1:3308:3308"
  oracle:
    ports:
      - "127.0.0.1:1521:1521"
  fts:
    ports:
      - "127.0.0.1:8446:8446"
      - "127.0.0.1:8449:8449"
  ftsdb:
    ports:
      - "127.0.0.1:3306:3306"
  xrd1:
    ports:
      - "127.0.0.1:1094:1094"
  xrd2:
    ports:
      - "127.0.0.1:1095:1095"
  xrd3:
    ports:
      - "127.0.0.1:1096:1096"
  xrd4:
    ports:
      - "127.0.0.1:1097:1097"
  xrd5:
    ports:
      - "127.0.0.1:1098:1098"
      - "127.0.0.1:8098:8098"
  web1:
    ports:
      - "127.0.0.1:8099:8099"
  minio:
    ports:
      - "127.0.0.1:9000:9000"
  ssh1:
    ports:
      - "127.0.0.1:2222:22"
  mongo:
    ports:
      - "127.0.0.1:27017:27017"
  elasticsearch_meta:
    ports:
      - "127.0.0.1:9400:9200"
      - "127.0.0.1:9500:9300"
  postgres:
    ports:
      - "127.0.0.1:5433:5433"
  logstash:
    ports:
      - "127.0.0.1:5044:5044"
  kibana:
    ports:
      - "127.0.0.1:5601:5601"
  grafana:
    ports:
      - "127.0.0.1:3000:3000"
  iam-db:
    ports:
      - "127.0.0.1:3307:3306"
  indigoiam:
    ports:
      - "127.0.0.1:9443:443"
  indigoiam-login-service:
    ports:
      - "127.0.0.1:8090:8090"
