# Copyright 2014-2018 CERN for the benefit of the ATLAS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Thomas Beermann, <thomas.beermann@cern.ch>, 2018

version: "2"
services:
  rucio:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "443:443"
    links:
      - mysql:mysql
    depends_on:
      - "mysql"
    command: ["httpd", "-D", "FOREGROUND"]
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_DATABASE=rucio
      - MYSQL_USER=rucio
      - MYSQL_PASSWORD=rucio
      - MYSQL_ROOT_HOST=%
